import { Command } from './types';

export const COMMANDS: Command[] = [
  { command: 'hdwwiz.cpl', description_ar: 'لإضافة مكوّن جديد في جهاز الكمبيوتر', description_en: 'Add new hardware wizard' },
  { command: 'control admintools', description_ar: 'أدوات مدير الجهاز', description_en: 'Administrative Tools' },
  { command: 'fsquirt', description_ar: 'إعدادات البلوتوث لنقل الملفات', description_en: 'Bluetooth File Transfer' },
  { command: 'calc', description_ar: 'الآلة الحاسبة', description_en: 'Calculator' },
  { command: 'certmgr.msc', description_ar: 'إدارة تصاريح الويندوز', description_en: 'Certificate Manager' },
  { command: 'charmap', description_ar: 'رموز إضافية للكتابة', description_en: 'Character Map' },
  { command: 'cmd', description_ar: 'الدوس الخاص بالويندوز', description_en: 'Command Prompt' },
  { command: 'dcomcnfg', description_ar: 'خدمات الويندوز والإعدادات', description_en: 'Component Services' },
  { command: 'compmgmt.msc', description_ar: 'إدارة الكمبيوتر', description_en: 'Computer Management' },
  { command: 'control', description_ar: 'لوحة تحكم الويندوز', description_en: 'Control Panel' },
  { command: 'timedate.cpl', description_ar: 'إعدادات التاريخ والوقت', description_en: 'Date and Time Settings' },
  { command: 'dxdiag', description_ar: 'تشخيص مشاكل الدايركت إكس ومعلومات عن النظام', description_en: 'DirectX Diagnostic Tool' },
  { command: 'cleanmgr', description_ar: 'تنظيف وإعداد البارتشن', description_en: 'Disk Cleanup' },
  { command: 'diskmgmt.msc', description_ar: 'إدارة وترتيب البارتشنات', description_en: 'Disk Management' },
  { command: 'control desktop', description_ar: 'إعدادات الشاشة والخلفية وحافظات الشاشة', description_en: 'Desktop Properties' },
  { command: 'desk.cpl', description_ar: 'إعدادات العرض', description_en: 'Display Settings' },
  { command: 'eventvwr.msc', description_ar: 'عرض الأحداث التي تمت في النظام', description_en: 'Event Viewer' },
  { command: 'control fonts', description_ar: 'إعدادات الخطوط', description_en: 'Fonts Folder' },
  { command: 'fonts', description_ar: 'إعدادات الخطوط أيضًا', description_en: 'Fonts Folder' },
  { command: 'iexplore', description_ar: 'متصفح الإنترنت إكسبلورر', description_en: 'Internet Explorer' },
  { command: 'inetcpl.cpl', description_ar: 'إعدادات الإنترنت والمتصفح', description_en: 'Internet Properties' },
  { command: 'control keyboard', description_ar: 'إعدادات لوحة المفاتيح', description_en: 'Keyboard Properties' },
  { command: 'logoff', description_ar: 'تسجيل الخروج (تبديل المستخدمين)', description_en: 'Log Off' },
  { command: 'mrt', description_ar: 'أداة إزالة البرمجيات الضارة', description_en: 'Malicious Software Removal Tool' },
  { command: 'mspaint', description_ar: 'برنامج الرسام', description_en: 'Microsoft Paint' },
  { command: 'control mouse', description_ar: 'إعدادات الماوس', description_en: 'Mouse Properties' },
  { command: 'notepad', description_ar: 'برنامج كتابة نصوص بسيط', description_en: 'Notepad' },
  { command: 'osk', description_ar: 'لوحة مفاتيح على الشاشة (في حالة تعطل الكيبورد)', description_en: 'On-Screen Keyboard' },
  { command: 'pbrush', description_ar: 'برنامج الرسام', description_en: 'Paint' },
  { command: 'powercfg.cpl', description_ar: 'إعدادات الطاقة والحفاظ عليها', description_en: 'Power Options' },
  { command: 'services.msc', description_ar: 'خدمات الويندوز والتحكم بها', description_en: 'Services' },
  { command: 'shutdown', description_ar: 'إيقاف تشغيل النظام', description_en: 'Shutdown Windows' },
  { command: 'mmsys.cpl', description_ar: 'إعدادات الصوت', description_en: 'Sound Settings' },
  { command: 'msinfo32', description_ar: 'معلومات حول النظام وجهاز الكمبيوتر', description_en: 'System Information' },
  { command: 'sysdm.cpl', description_ar: 'خصائص النظام وإعدادات الجهاز', description_en: 'System Properties' },
  { command: 'explorer', description_ar: 'مستكشف الملفات والمجلدات', description_en: 'Windows Explorer' },
  { command: 'magnify', description_ar: 'العدسة المكبرة', description_en: 'Magnifier' },
  { command: 'wmimgmt.msc', description_ar: 'إعداد إدارة نظام الويندوز', description_en: 'Windows Management Instrumentation' },
  { command: 'winver', description_ar: 'معرفة إصدار الويندوز', description_en: 'Windows Version' },
  { command: 'write', description_ar: 'برنامج الكتابة (البلوك نوت المطوّر)', description_en: 'WordPad' },
  { command: 'msconfig', description_ar: 'أداة إعداد النظام (تشغيل البرامج مع الإقلاع)', description_en: 'System Configuration' },
  { command: 'taskman', description_ar: 'عرض والتحكم بالبرامج المفتوحة في شريط المهام', description_en: 'Task Manager' },
  { command: 'defrag', description_ar: 'ترتيب الهارد ديسك لزيادة السرعة', description_en: 'Defragment hard disk' },
  { command: 'recent', description_ar: 'فتح مجلد الملفات التي تم فتحها مؤخرًا', description_en: 'Recent Items' },
];
